#!/usr/bin/env ruby

require 'bundler/setup'
require 'dora'

include Dora

module Clean
  class << self
    def number(string)
      ['+', '-', ' '].each { |pattern| string.gsub!(pattern, '') }
      string
    end
  end
end

puts 'Number?'
username = Clean.number(gets.chomp)

w = Client.new username
begin
  response = w.check_credentials
rescue RegistrationError => error
  puts error
rescue => error
  puts error.inspect
end
puts response

