#!/usr/bin/env ruby

require 'bundler/setup'
require 'chat_api'

include Dora

module Clean
  class << self
    def number(string)
      ['+', '-', ' '].each { |pattern| string.gsub!(pattern, '') }
      string
    end
  end
end

puts 'Number?'
username = Clean.number(gets.chomp)

puts 'Get sms or voice?'
check = false
option = ''
until check do
  option = Clean.number(gets.chomp)
  if option == 'sms' || option == 'voice'
    check = true
  else
    puts "Sorry, you typed wrong response. Do you want receive 'sms' or 'voice'?"
  end
end

w = Client.new(username)
begin
  response = w.code_request(option)
rescue ChatAPIError => error
  puts error.inspect
  exit
rescue => error
  puts error.inspect
  exit
end
puts response

puts 'Insert received code: '
code = Clean.number(gets.chomp)

begin
  result = w.code_register(code)
rescue ChatAPIError => error
  puts error.inspect
rescue => error
  puts error.inspect
end

puts result
